MODEL_INFO:
  DEVICE: "cpu"
  CONFIG:
    embed_dim: 768
    patch_size: 32
    seq_length: 2560
    in_channels: 12
    encoder: "vit_encoder"
    merge_mode: "projection"
    num_classes: 12
  MODEL_PATHS:
    - "/mnt/home/bgk/macai-model-experimental/_kimbg_code/SynAI_v2/outputs/checkpoint/CL_step3-TRN-MacAI_v1_2-0819 copy 21/0fold/Best_AUPRC-Ep_3-Lo_0.082-M0_0.793-M1_0.494.pth"
    - "/mnt/home/bgk/macai-model-experimental/_kimbg_code/SynAI_v2/outputs/checkpoint/CL_step3-TRN-MacAI_v1_2-0819 copy 21/0fold/Best_AUROC-Ep_7-Lo_0.082-M0_0.800-M1_0.493.pth"
    - "/mnt/home/bgk/macai-model-experimental/_kimbg_code/SynAI_v2/outputs/checkpoint/CL_step3-TRN-MacAI_v1_2-0819 copy 21/0fold/Best_loss-Ep_5-Lo_0.082-M0_0.797-M1_0.493.pth"
  AF_CAL_MODEL_PATH: "/mnt/home/bgk/macai-engine-v1/trained_models/v1.3.0/calibration_model-AF.pkl"
  CIA_CAL_MODEL_PATH: "/mnt/home/bgk/macai-engine-v1/trained_models/v1.3.0/calibration_model-CIA.pkl"
  OUTPUT_CLS_INFO:
    cls_names:
      - "ECG_event_3d_AFIB_AFL-keyword_v2_onset"
      - "ECG_event_3d_CIA-keyword_v2_onset"
      - "ECG_event_7d_AFIB_AFL-keyword_v2_onset"
      - "ECG_event_7d_CIA-keyword_v2_onset"
      - "ECG_event_14d_AFIB_AFL-keyword_v2_onset"
      - "ECG_event_14d_CIA-keyword_v2_onset"
      - "ECG_event_30d_AFIB_AFL-keyword_v2_onset"
      - "ECG_event_30d_CIA-keyword_v2_onset"
      - "ECG_event_90d_AFIB_AFL-keyword_v2_onset"
      - "ECG_event_90d_CIA-keyword_v2_onset"
      - "AFIB_AFL-keyword_v2"
      - "CIA-keyword_v2"
    target_cls:
      AF: "ECG_event_14d_AFIB_AFL-keyword_v2_onset"
      CIA: "ECG_event_14d_CIA-keyword_v2_onset"  
  RISK_THRESHOLD:
    af_high_g_thr: 0.18594001505695362
    af_inter_g_thr: 0.09283757956391994
    cia_high_g_thr: 0.6134156782179706
    cia_inter_g_thr: 0.39689483565475614

DATA_INFO:
  XML_INFO:
    xml_paths:
      - "/mnt/home/bgk/macai-engine-v1/data/samples/xmls/10144268_2024-06-02_2024060214062189_2024060214053964.xml"
      - "/mnt/home/bgk/macai-engine-v1/data/samples/xmls/10203160_2023-10-04_2023100411441625_2023101110031840.xml"
      - "/mnt/home/bgk/macai-engine-v1/data/samples/xmls/10302870_2023-10-17_2023101716092374_2023101716095795.xml"
    api_url: "http://localhost:18003/parse/parse_xml"
  NPY_INFO:
    npy_paths:
      - "/mnt/home/bgk/macai-engine-v1/data/samples/npys/10144268_2024-06-02_2024060214062189_2024060214053964.npy"
      - "/mnt/home/bgk/macai-engine-v1/data/samples/npys/10203160_2023-10-04_2023100411441625_2023101110031840.npy"
      - "/mnt/home/bgk/macai-engine-v1/data/samples/npys/10302870_2023-10-17_2023101716092374_2023101716095795.npy"
  PREPROCESS:
    do_bandpass:
      lowcut: 0.5
      highcut: 40.0
      order: 3
    target_fs: 256
    do_normalize: false
  TRANSFORMS:
    val:
      - type: "NormalizeECG"
        method: "tanh"
        scope: "lead-wise"
        scale: 1